apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  name: tls-minio-dev
  labels:
    f5cr: "true"
  namespace: minio-f5-dev
spec:
  tls:
    termination: edge
    clientSSL: /Common/clientssl-vnpt.vn
    reference: bigip             # --> reference profiles created in BIG-IP by User
  hosts:
  - storage-f5dev.vnpt.vn
